In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [11]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a2[:,3]

array([ 4,  8, 12])

In [12]:
a2[2]

array([ 9, 10, 11, 12])

In [15]:
a.shape
len(a.shape) == a.ndim

True

In [13]:
a2.ndim

2

In [19]:
a.size
import math
a.size == math.prod(a.shape)

True

In [20]:
a.dtype

dtype('int64')

In [39]:
ze = np.zeros(3)
ze.shape
zone = np.ones(4)
zone
ztwo = np.arange(2,11,3)
ztwo
zthree = np.linspace(1,10, num=5)
zthree
x1 = np.ones(3, dtype=np.int64)
x1.dtype

dtype('int64')

In [40]:
arr = np.array([2,1,3,0])
np.sort(arr)

array([0, 1, 2, 3])

In [43]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim
array_example.shape
array_example.size

24

In [82]:
a = np.arange(6)
a
b = a.reshape(3,2)
b
c = np.reshape(b, newshape=(2,3), order='C')
c
# d = c[np.newaxis, :]
# e = c[:, np.newaxis]
# e[1,0,0]

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
a
a2 = a[np.newaxis, :]
a2.ndim
a3 = a2[np.newaxis, :]
a3.ndim
a3

array([[[0, 1, 2, 3, 4, 5]]])

In [60]:
row_vector = a[np.newaxis, :]
row_vector.shape
row_vector
col_vector = a[:, np.newaxis]
col_vector.shape
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [71]:
b = np.expand_dims(a, 1)
c = np.expand_dims(b, 1)
d = np.expand_dims(c,1)
a 

array([0, 1, 2, 3, 4, 5])

In [94]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (a > 6)
a[five_up]
a[a>6]
a[a%2==0]
b = np.nonzero(a<6)
# c = list(zip(b[0],b[1]))
# c
a[b]
# a[a<6]

array([1, 2, 3, 4, 5])

In [102]:
x = np.arange(1, 25)
x
y = np.hsplit(x,3)
y

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]